export const START_WITH_NAME_REQUEST = "START_WITH_NAME_REQUEST";
export type START_WITH_NAME_REQUEST = typeof START_WITH_NAME_REQUEST;

export const START_WITH_NAME_SUCCESS = "START_WITH_NAME_SUCCESS";
export type START_WITH_NAME_SUCCESS = typeof START_WITH_NAME_SUCCESS;

export const START_WITH_NAME_FAILURE = "START_WITH_NAME_FAILURE";
export type START_WITH_NAME_FAILURE = typeof START_WITH_NAME_FAILURE;
