export const FETCH_CHARACTERS_REQUEST = "FETCH_CHARACTERS_REQUEST";
export type FETCH_CHARACTERS_REQUEST = typeof FETCH_CHARACTERS_REQUEST;

export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export type FETCH_CHARACTERS_SUCCESS = typeof FETCH_CHARACTERS_SUCCESS;

export const FETCH_CHARACTERS_FAILURE = "FETCH_CHARACTERS_FAILURE";
export type FETCH_CHARACTERS_FAILURE = typeof FETCH_CHARACTERS_FAILURE;
